import { defineStore } from 'pinia';

export const useCourseStore = defineStore('course', {
  state: () => ({
    // All courses generated by the user
    user_courses: JSON.parse(localStorage.getItem('user_courses')) || [],
    // Currently active course (the one being played)
    currentCourse: JSON.parse(localStorage.getItem('current_course')) || null,
    loading: false,
    error: null,
  }),
  actions: {
    setCourse(course) {
      this.currentCourse = course;
      localStorage.setItem('current_course', JSON.stringify(course));
      
      // Also ensure it's in user_courses if not already
      this.addCourse(course);
    },
    
    addCourse(course) {
      const exists = this.user_courses.find(c => c.id === course.id || c.title === course.title);
      if (!exists) {
        // Initialize progress if new
        if (!course.completed_steps) course.completed_steps = [];
        if (!course.progress) course.progress = 0;
        if (!course.id) course.id = Date.now().toString(); // Fallback ID
        if (!course.category) course.category = 'General';
        
        this.user_courses.unshift(course);
        this.saveToStorage();
      }
    },
    
    updateProgress(courseId, stepId) {
      const course = this.user_courses.find(c => c.id === courseId);
      if (course) {
        if (!course.completed_steps) course.completed_steps = [];
        
        const index = course.completed_steps.indexOf(stepId);
        if (index === -1) {
          course.completed_steps.push(stepId);
        } else {
          // Toggle if needed, but usually we just mark as done
          // course.completed_steps.splice(index, 1);
        }
        
        // Calculate percentage
        course.progress = Math.round((course.completed_steps.length / course.steps.length) * 100);
        
        // Update current course if it's the one being played
        if (this.currentCourse && this.currentCourse.id === courseId) {
          this.currentCourse = { ...course };
          localStorage.setItem('current_course', JSON.stringify(this.currentCourse));
        }
        
        this.saveToStorage();
      }
    },

    deleteCourse(courseId) {
      this.user_courses = this.user_courses.filter(c => c.id !== courseId);
      if (this.currentCourse?.id === courseId) {
        this.clearCourse();
      }
      this.saveToStorage();
    },

    saveToStorage() {
      localStorage.setItem('user_courses', JSON.stringify(this.user_courses));
    },

    clearCourse() {
      this.currentCourse = null;
      localStorage.removeItem('current_course');
    }
  },
});
